name: Moin
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile Moin
        run: gcc -o Moin Moin.c -lssl -lcrypto -lpthread
      - name: Make executable
        run: chmod +x Moin
      - name: Run Moin
        run: ./Moin 98.70.107.243 19260 300
